export const expandedTeams = [
 ['warnatz','Klaus Warnatz · Freiburg CCI','Germany','CVID · GLILD · clinical immunology','CVID、GLILD 与临床免疫','https://www.uniklinik-freiburg.de/cci/forschung/klaus-warnatz.html'],
 ['grimbacher','Bodo Grimbacher · Freiburg CCI','Germany','Genetic causes of immunodeficiency and immune dysregulation','免疫缺陷与免疫失调的遗传机制','https://www.uniklinik-freiburg.de/cci/forschung/bodo-grimbacher.html'],
 ['cunningham-rundles','Charlotte Cunningham-Rundles · Mount Sinai','United States','Primary immunodeficiency research and clinical immunology','原发性免疫缺陷研究与临床免疫','https://profiles.mountsinai.org/charlotte-cunningham-rundles'],
 ['tangye','Stuart Tangye Lab · Garvan','Australia','B-cell and T-cell biology, antibody responses and IEI','B/T 细胞生物学、抗体应答与 IEI','https://www.garvan.org.au/research/labs/immunology-and-immunodeficiency'],
 ['hambleton','Sophie Hambleton · Newcastle University','United Kingdom','Cellular and molecular causes of childhood IEI','儿童 IEI 的细胞与分子机制','https://www.ncl.ac.uk/medical-sciences/people/profile/sophiehambleton.html'],
 ['sullivan','Kathleen Sullivan Laboratory · CHOP','United States','Rare immunodeficiencies and immune dysregulation','罕见免疫缺陷与免疫调节异常','https://www.research.chop.edu/sullivan-laboratory'],
 ['casanova','Jean-Laurent Casanova · Rockefeller University','United States','Human genetics of susceptibility to infectious disease','感染易感性的人类遗传学','https://www.rockefeller.edu/research/2247-casanova-laboratory-2/'],
 ['meyts','Isabelle Meyts · KU Leuven','Belgium','Inborn Errors of Immunity research group','先天性免疫错误研究组','https://www.kuleuven.be/wieiswie/en/unit/regional/50546724'],
 ['cincinnati','Cincinnati Children’s · Immune Deficiencies and Dysregulation','United States','Specialist team with research and clinical-trial pathways','免疫缺陷和免疫失调专科团队及研究入口','https://www.cincinnatichildrens.org/service/i/immune-deficiency'],
 ['newcastle-hi','Haematopoiesis and Immunity Laboratory · Newcastle','United Kingdom','Dendritic-cell and monocyte immunodeficiencies','树突状细胞与单核细胞免疫缺陷','https://research.ncl.ac.uk/hilab/']
];
export function expandedCards(lang){return expandedTeams.map(([id,name,country,en,zh,url])=>`<article class="panel" id="team-${id}"><small>${country} · ${lang==='zh'?'研究团队 / 专科团队':'Research / specialist team'}</small><h2>${name}</h2><p>${lang==='zh'?zh:en}</p><p><a href="${url}" target="_blank" rel="noopener">${lang==='zh'?'机构介绍与研究资料':'Institution profile & research'} ↗</a></p></article>`).join('');}
export function bindDirectory(){const host=document.querySelector('[data-team-directory]');if(!host)return;const search=document.querySelector('#team-search');const country=document.querySelector('#team-country');const cards=[...host.querySelectorAll(':scope > article')];const update=()=>{let count=0;for(const card of cards){const text=card.textContent.toLowerCase();card.hidden=!(text.includes(search.value.toLowerCase().trim())&&(!country.value||text.includes(country.value.toLowerCase())));if(!card.hidden)count++;}document.querySelector('#team-count').textContent=count;};search.oninput=update;country.onchange=update;update();}
